spring:
  cache:
    cache-names: tapo-p100-plug-cache
  task:
    scheduling:
      pool:
        size: 3
application:
  thermostat:
    delayInMilliseconds: 60000 # 1 min
  readings-publisher:
    delayInMilliseconds: 330000 # 5 min and 30 secs
server:
  servlet:
    context-path: /cloud-thermostat/api
thirdparty:
  brewers-friend:
    api-key:
